# Generated by Django 4.0.4 on 2022-05-30 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('street', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('zip_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('current_location', models.CharField(default='', max_length=255)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing_spots_backend.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FishingSpots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFished', models.BooleanField(default=False)),
                ('fish_types', models.CharField(default='', max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('images', models.FileField(null=True, upload_to='')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing_spots_backend.address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fishing_spots_backend.customers')),
            ],
        ),
    ]
