# Generated by Django 4.0.4 on 2022-07-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_spots_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishingspots',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='fishingspots',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.AddField(
            model_name='fishingspots',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
