# Generated by Django 4.0.4 on 2022-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_spots_backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directions',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
