# Generated by Django 4.0.4 on 2022-05-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_spots_backend', '0002_delete_directions_remove_customers_name_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fishingspots',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fishingspots',
            name='fish_types',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fishingspots',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fishingspots',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fishingspots',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fishingspots',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitedfishingspots',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitedfishingspots',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitedfishingspots',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitedfishingspots',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitedfishingspots',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
